name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # Run it if sync doesn't update fcitx5 part (i.e. only updates google/mozc)

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm base-devel cmake clang ninja extra-cmake-modules fmt libuv git python

      - uses: actions/checkout@v7
        with:
          path: fcitx5-mozc
          submodules: recursive

      - name: Patch
        working-directory: fcitx5-mozc
        run: |
          git apply --directory=protobuf patches/protobuf.patch
          mkdir -p build/data_manager/oss
          curl -LO --output-dir build/data_manager/oss https://github.com/fcitx-contrib/fcitx5-mozc/releases/download/latest/mozc_data.inc

      - uses: actions/checkout@v7
        with:
          repository: fcitx/fcitx5
          path: fcitx5

      - name: Cache fcitx5 data files
        uses: actions/cache@v6
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt')}}

      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off -DENABLE_X11=Off -DENABLE_WAYLAND=Off -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off -DENABLE_SERVER=Off -DENABLE_EMOJI=Off -DUSE_SYSTEMD=Off -DENABLE_TEST=OFF -DENABLE_TESTING_ADDONS=OFF

      - name: Build and Install fcitx5-mozc
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5-mozc

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
