name: prebuild

on:
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Setup User
        run: |
          useradd -m builduser

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git bazel python

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Patch
        run: |
          # Accelerate build by removing irrelevant compilers.
          git apply --directory=protobuf patches/protobuf.patch

      - name: Build data
        working-directory: mozc/src
        run: |
          chown -R builduser:builduser .
          sudo -u builduser bazel build --config oss_linux --host_cxxopt=-Wno-uninitialized //data_manager/oss:mozc_data.inc

      - name: Release data
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            mozc/src/bazel-bin/data_manager/oss/mozc_data.inc
            mozc/src/bazel-bin/data_manager/oss/mozc.data

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
